name: "Clang: Build C"
description: "Building C code with specific Xcode version"
inputs:
  xcode-version: # id of input
    description: "Xcode Version"
    required: true
# outputs:
# random-number:
#   description: "Random number"
#   value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Print toolchain versions
      shell: bash
      run: |
        xcodebuild -version
        swift --version
        clang --version

    - name: Build (x86_64-apple-ios-macabi)
      shell: bash
      run: |
        clang -target x86_64-apple-ios-macabi main.c

    - name: Build (x86_64-apple-ios14.0-macabi)
      shell: bash
      run: |
        clang -target x86_64-apple-ios14.0-macabi main.c

    - name: Build (x86_64-apple-ios13.0-macabi)
      shell: bash
      run: |
        clang -target x86_64-apple-ios13.0-macabi main.c
