name: Xcode-clang

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Matrix with different Xcode versions

jobs:
  build:
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        xcode: [13.0.0, 13.1.0, 13.2.1]

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Print toolchain versions
        run: |
          xcodebuild -version
          swift --version
          clang --version

      - name: Build (x86_64-apple-ios-macabi)
        run: |
          clang -target x86_64-apple-ios-macabi main.c

      - name: Build (x86_64-apple-ios14.0-macabi)
        run: |
          clang -target x86_64-apple-ios14.0-macabi main.c

      - name: Build (x86_64-apple-ios13.0-macabi)
        run: |
          clang -target x86_64-apple-ios13.0-macabi main.c
