name: Xcode-clang

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Matrix with different Xcode versions

jobs:
  build-macos10-15:
    strategy:
      fail-fast: false
      matrix:
        xcode:
          [
            11.2.1,
            11.3.1,
            11.4.1,
            11.5.0,
            11.6.0,
            12.0.1,
            12.1.0,
            12.2.0,
            12.3.0,
            12.4.0,
          ]
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/clang-build-c
        name: Build
        with:
          platform: ${{ matrix.xcode }}

  build-macos-11:
    strategy:
      fail-fast: false
      matrix:
        xcode: [13.0.0, 13.1.0, 13.2.1]
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/clang-build-c
        name: Build
        with:
          platform: ${{ matrix.xcode }}

  build-macos-12:
    strategy:
      fail-fast: false
      matrix:
        xcode: [13.3.1, 13.4.1, 14.0.1, 14.1.0, 14.2.0]
        os: [macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/clang-build-c
        name: Build
        with:
          platform: ${{ matrix.xcode }}
